//+build !swipe

// Code generated by Swipe v2.0.0-rc1. DO NOT EDIT.

package transport

import (
	"context"
	"github.com/go-kit/kit/endpoint"
	"github.com/kkucherenkov/golang-test-task/controller"
)

func MakeScrapperControllerGetByDomainEndpoint(s controller.ScrapperController) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(GetByDomainRequest)
		latency, code, err := s.GetByDomain(ctx, req.Domain)
		if err != nil {
			return nil, err
		}
		return GetByDomainResponse{Latency: latency, Code: code}, nil
	}

}

func MakeScrapperControllerGetCountEndpoint(s controller.ScrapperController) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		result := s.GetCount(ctx)
		return result, nil
	}

}

func MakeScrapperControllerGetMaxLatencyEndpoint(s controller.ScrapperController) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		domain, latency, code, err := s.GetMaxLatency(ctx)
		if err != nil {
			return nil, err
		}
		return GetMaxLatencyResponse{Domain: domain, Latency: latency, Code: code}, nil
	}

}

func MakeScrapperControllerGetMinLatencyEndpoint(s controller.ScrapperController) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		domain, latency, code, err := s.GetMinLatency(ctx)
		if err != nil {
			return nil, err
		}
		return GetMinLatencyResponse{Domain: domain, Latency: latency, Code: code}, nil
	}

}

type ScrapperControllerEndpointSet struct {
	GetByDomainEndpoint   endpoint.Endpoint
	GetCountEndpoint      endpoint.Endpoint
	GetMaxLatencyEndpoint endpoint.Endpoint
	GetMinLatencyEndpoint endpoint.Endpoint
}

func MakeScrapperControllerEndpointSet(svc controller.ScrapperController) ScrapperControllerEndpointSet {
	return ScrapperControllerEndpointSet{
		GetByDomainEndpoint:   MakeScrapperControllerGetByDomainEndpoint(svc),
		GetCountEndpoint:      MakeScrapperControllerGetCountEndpoint(svc),
		GetMaxLatencyEndpoint: MakeScrapperControllerGetMaxLatencyEndpoint(svc),
		GetMinLatencyEndpoint: MakeScrapperControllerGetMinLatencyEndpoint(svc),
	}
}

type GetByDomainRequest struct {
	Domain string `json:"domain"`
}
type GetByDomainResponse struct {
	Latency int64 `json:"latency"`
	Code    int   `json:"code"`
}
type GetMaxLatencyResponse struct {
	Domain  string `json:"domain"`
	Latency int64  `json:"latency"`
	Code    int    `json:"code"`
}
type GetMinLatencyResponse struct {
	Domain  string `json:"domain"`
	Latency int64  `json:"latency"`
	Code    int    `json:"code"`
}
