//+build !swipe

// Code generated by Swipe v2.0.0-rc1. DO NOT EDIT.

package transport

import (
	"github.com/go-kit/kit/endpoint"
	"github.com/l-vitaly/go-kit/transport/http/jsonrpc"
)

type httpError struct {
	code    int
	data    interface{}
	message string
}

func (e *httpError) Error() string {
	return e.message
}
func (e *httpError) StatusCode() int {
	return e.code
}
func (e *httpError) ErrorData() interface{} {
	return e.data
}
func (e *httpError) SetErrorData(data interface{}) {
	e.data = data
}
func (e *httpError) SetErrorMessage(message string) {
	e.message = message
}
func scrapperControllerGetByDomainErrorDecode(code int, message string, data interface{}) (err error) {
	switch code {
	default:
		err = &httpError{code: code}
	}
	if err, ok := err.(interface{ SetErrorData(data interface{}) }); ok {
		err.SetErrorData(data)
	}
	if err, ok := err.(interface{ SetErrorMessage(message string) }); ok {
		err.SetErrorMessage(message)
	}
	return
}

func scrapperControllerGetCountErrorDecode(code int, message string, data interface{}) (err error) {
	switch code {
	default:
		err = &httpError{code: code}
	}
	if err, ok := err.(interface{ SetErrorData(data interface{}) }); ok {
		err.SetErrorData(data)
	}
	if err, ok := err.(interface{ SetErrorMessage(message string) }); ok {
		err.SetErrorMessage(message)
	}
	return
}

func scrapperControllerGetMaxLatencyErrorDecode(code int, message string, data interface{}) (err error) {
	switch code {
	default:
		err = &httpError{code: code}
	}
	if err, ok := err.(interface{ SetErrorData(data interface{}) }); ok {
		err.SetErrorData(data)
	}
	if err, ok := err.(interface{ SetErrorMessage(message string) }); ok {
		err.SetErrorMessage(message)
	}
	return
}

func scrapperControllerGetMinLatencyErrorDecode(code int, message string, data interface{}) (err error) {
	switch code {
	default:
		err = &httpError{code: code}
	}
	if err, ok := err.(interface{ SetErrorData(data interface{}) }); ok {
		err.SetErrorData(data)
	}
	if err, ok := err.(interface{ SetErrorMessage(message string) }); ok {
		err.SetErrorMessage(message)
	}
	return
}

func middlewareChain(middlewares []endpoint.Middleware) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		if len(middlewares) == 0 {
			return next
		}
		outer := middlewares[0]
		others := middlewares[1:]
		for i := len(others) - 1; i >= 0; i-- {
			next = others[i](next)
		}
		return outer(next)
	}
}
func GenericServerOptions(v ...jsonrpc.ServerOption) ServerOption {
	return func(o *serverOpts) { o.genericServerOption = v }
}

func GenericServerEndpointMiddlewares(v ...endpoint.Middleware) ServerOption {
	return func(o *serverOpts) { o.genericEndpointMiddleware = v }
}

type ServerOption func(*serverOpts)
type serverOpts struct {
	genericServerOption                               []jsonrpc.ServerOption
	genericEndpointMiddleware                         []endpoint.Middleware
	scrapperControllerGetByDomainServerOption         []jsonrpc.ServerOption
	scrapperControllerGetByDomainEndpointMiddleware   []endpoint.Middleware
	scrapperControllerGetCountServerOption            []jsonrpc.ServerOption
	scrapperControllerGetCountEndpointMiddleware      []endpoint.Middleware
	scrapperControllerGetMaxLatencyServerOption       []jsonrpc.ServerOption
	scrapperControllerGetMaxLatencyEndpointMiddleware []endpoint.Middleware
	scrapperControllerGetMinLatencyServerOption       []jsonrpc.ServerOption
	scrapperControllerGetMinLatencyEndpointMiddleware []endpoint.Middleware
}

func ScrapperControllerGetByDomainServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetByDomainServerOption = opt }
}

func ScrapperControllerGetByDomainServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetByDomainEndpointMiddleware = opt }
}

func ScrapperControllerGetCountServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetCountServerOption = opt }
}

func ScrapperControllerGetCountServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetCountEndpointMiddleware = opt }
}

func ScrapperControllerGetMaxLatencyServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetMaxLatencyServerOption = opt }
}

func ScrapperControllerGetMaxLatencyServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetMaxLatencyEndpointMiddleware = opt }
}

func ScrapperControllerGetMinLatencyServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetMinLatencyServerOption = opt }
}

func ScrapperControllerGetMinLatencyServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.scrapperControllerGetMinLatencyEndpointMiddleware = opt }
}
