//+build !swipe

// Code generated by Swipe v2.0.0-rc1. DO NOT EDIT.

package transport

import (
	"context"
	"github.com/go-kit/kit/metrics"
	prometheus2 "github.com/go-kit/kit/metrics/prometheus"
	"github.com/kkucherenkov/golang-test-task/controller"
	"github.com/prometheus/client_golang/prometheus"
	"time"
)

type instrumentingOpts struct {
	requestCount   metrics.Counter
	requestLatency metrics.Histogram
	namespace      string
	subsystem      string
}

type InstrumentingOption func(*instrumentingOpts)

func Namespace(v string) InstrumentingOption {
	return func(o *instrumentingOpts) {
		o.namespace = v
	}
}

func Subsystem(v string) InstrumentingOption {
	return func(o *instrumentingOpts) {
		o.subsystem = v
	}
}

func RequestLatency(requestLatency metrics.Histogram) InstrumentingOption {
	return func(o *instrumentingOpts) {
		o.requestLatency = requestLatency
	}
}

func RequestCount(requestCount metrics.Counter) InstrumentingOption {
	return func(o *instrumentingOpts) {
		o.requestCount = requestCount
	}
}

type ScrapperControllerInstrumentingMiddleware struct {
	next controller.ScrapperController
	opts *instrumentingOpts
}

func (s *ScrapperControllerInstrumentingMiddleware) GetByDomain(ctx context.Context, domain string) (int64, int, error) {
	defer func(begin time.Time) {
		s.opts.requestCount.With("method", "GetByDomain").Add(1)
		s.opts.requestLatency.With("method", "GetByDomain").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.GetByDomain(ctx, domain)
}

func (s *ScrapperControllerInstrumentingMiddleware) GetCount(ctx context.Context) int {
	defer func(begin time.Time) {
		s.opts.requestCount.With("method", "GetCount").Add(1)
		s.opts.requestLatency.With("method", "GetCount").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.GetCount(ctx)
}

func (s *ScrapperControllerInstrumentingMiddleware) GetMaxLatency(ctx context.Context) (string, int64, int, error) {
	defer func(begin time.Time) {
		s.opts.requestCount.With("method", "GetMaxLatency").Add(1)
		s.opts.requestLatency.With("method", "GetMaxLatency").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.GetMaxLatency(ctx)
}

func (s *ScrapperControllerInstrumentingMiddleware) GetMinLatency(ctx context.Context) (string, int64, int, error) {
	defer func(begin time.Time) {
		s.opts.requestCount.With("method", "GetMinLatency").Add(1)
		s.opts.requestLatency.With("method", "GetMinLatency").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.GetMinLatency(ctx)
}

func NewInstrumentingScrapperControllerMiddleware(s controller.ScrapperController, opts ...InstrumentingOption) controller.ScrapperController {
	i := &ScrapperControllerInstrumentingMiddleware{next: s, opts: &instrumentingOpts{}}
	for _, o := range opts {
		o(i.opts)
	}
	if i.opts.requestCount == nil {
		i.opts.requestCount = prometheus2.NewCounterFrom(prometheus.CounterOpts{
			Namespace: i.opts.namespace,
			Subsystem: i.opts.subsystem,
			Name:      "request_count",
			Help:      "Number of requests received.",
		}, []string{"method"})

	}
	if i.opts.requestLatency == nil {
		i.opts.requestLatency = prometheus2.NewSummaryFrom(prometheus.SummaryOpts{
			Namespace: i.opts.namespace,
			Subsystem: i.opts.subsystem,
			Name:      "request_latency_microseconds",
			Help:      "Total duration of requests in microseconds.",
		}, []string{"method"})

	}
	return i
}
